version: '3.7'

services:
  pihole:
    image: letfn/pihole
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq:/etc/dnsmasq.d
    environment:
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    ports:
      - 169.254.32.1:53:53/tcp
      - 169.254.32.1:53:53/udp
      - 169.254.32.1:8080:80/tcp
