version: '3.7'

services:
  pihole:
    image: defn/pihole
    volumes:
      - ${PIHOLE_MOUNT}/pihole:/etc/pihole
      - ${PIHOLE_MOUNT}/dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 8.8.8.8
    env_file: ./.env
    labels:
      - "SERVICE_NAME=pihole"
      - "app=pihole"
      - "zone=kitt"
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.rule=HostRegexp(`pihole.{domain:.+}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.53
    ports:
      - 80
    restart: always

networks:
  default:
    external:
      name: kitt_default
